# Generated by Django 4.1.3 on 2022-12-06 16:30

import bank_cards.cards.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.CharField(default=bank_cards.cards.models.get_card_series, max_length=4)),
                ('card_number', models.CharField(default=bank_cards.cards.models.get_card_number, max_length=12)),
                ('status', models.CharField(choices=[('Активирована', 'Активирована'), ('Деактивирована', 'Деактивирована'), ('Просрочена', 'Просрочена')], default='Активирована', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('how_long', models.CharField(choices=[('1', '1 месяц'), ('6', '6 месяцев'), ('12', '1 год')], default='1', max_length=16)),
                ('amount', models.FloatField(default=1000.0)),
            ],
        ),
    ]
